name: ai_human_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - gensim
  - pip
  - pip:
    - matplotlib
    - seaborn